workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1


artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - build/app/outputs/flutter-apk/app-x86_64-release.apk
      - sha256_sums/sha256-app-release.apk.txt
      - sha256_sums/sha256-app-arm64-v8a-release.apk.txt
      - sha256_sums/sha256-app-armeabi-v7a-release.apk.txt
      - sha256_sums/sha256-app-x86_64-release.apk.txt
